/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/bird/model.glb 
Author: Natural History Museum of Los Angeles County (https://sketchfab.com/NHMLA)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-teratorn-teratornis-merriami-cf3b18862d1849168c31f7fd6964c925
Title: Low poly teratorn (Teratornis merriami)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/model.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" position={[-0.046, 4.217, 11.418]} rotation={[-Math.PI / 2, 0, 0]} scale={0.012}>
          <group name="5a0594a3e0d9449681537f0babcb74effbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Teratorn">
                  <group name="Geometry">
                    <group name="Teratorn_1" />
                  </group>
                  <group name="Main">
                    <group name="DeformationSystem">
                      <group name="Object_9">
                        <primitive object={nodes._rootJoint} />
                        <group name="Object_11" />
                        <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Teratorn} skeleton={nodes.Object_12.skeleton} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
